### PR TITLE
Feature/workflows

### PR DESCRIPTION
**Pull request by willeagren**
We need to perform PR before testing, to test the workflow... I know, not the best solution. But doesn't matter if the rust `Build and test` workflow fails or not, we just want it to run properly on PR and push to master.

### CODE REVIEW

**Comment by willeagren** [comment]
Restored branch because we might want to set up Go (or some other) workflow, and so we can reuse this. Delete branch again if you disagree, and I wont restore it again.

**Comment by Ignalina** [comment]
ah sorry didnt realize i deleted :)  i just pressed "ok" :) :)

**Comment by Ignalina** [comment]
we could do zoom meeting tomorrow , or at wok , i need to grasp the UI of github  ,,, atm I just press "ok" :)

**Comment by willeagren** [comment]
i will be in office tomorrow, should have spare time and we can look at git stuffs :)

**Comment by Ignalina** [comment]
feel free to at workflow / build stuff if you got access , ive never tried this at github.

Im adding you to https://jenkins.x14.se   , its prob the fastest build server alive   , 12 core ,dedicated pcie 4.0 nvme disk :) 120gb ram  .

**Pull request merged**
